#!/usr/bin/env python3
"""Fail when a documented benchmark count drifts from the actual corpus.

Stale numbers are the single fastest way to lose the trust of a reader who
checks — and answer engines quote whatever number they find first. This script
derives the ground truth from ``benchmark/`` itself, writes it to
``benchmark/BENCHMARK_FACTS.json``, and then asserts that every public surface
(README, docs, ``llms.txt``, citation metadata) agrees with it.

Usage::

    python scripts/check_facts.py            # verify, exit 1 on drift
    python scripts/check_facts.py --write    # refresh BENCHMARK_FACTS.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FACTS_PATH = ROOT / "benchmark" / "BENCHMARK_FACTS.json"


def derive_facts() -> dict[str, object]:
    """Read the corpus on disk and return the authoritative counts."""
    spec_dir = ROOT / "benchmark" / "tasks" / "specs"
    specs = sorted(spec_dir.glob("*.json"))

    splits: Counter[str] = Counter()
    qcats: set[str] = set()
    roles: set[str] = set()
    for spec_path in specs:
        spec = json.loads(spec_path.read_text())
        splits[str(spec.get("benchmark_split", "unspecified"))] += 1
        if qcat := spec.get("qcat"):
            qcats.add(str(qcat))
        if role := spec.get("role"):
            roles.add(str(role))

    env_dirs = sorted(p for p in (ROOT / "benchmark" / "environments").glob("env_*") if p.is_dir())
    m100_envs = [p for p in env_dirs if p.name.startswith("env_m100_")]
    m100_tasks = [p for p in specs if p.name.startswith("M100_")]

    version = _project_version()

    return {
        "_comment": (
            "Generated by scripts/check_facts.py. Single source of truth for every "
            "count quoted in the README, the docs site, and llms.txt. Do not hand-edit."
        ),
        "version": version,
        "tasks_total": len(specs),
        "tasks_synthetic": len(specs) - len(m100_tasks),
        "tasks_m100": len(m100_tasks),
        "tasks_dev": splits.get("dev", 0),
        "tasks_test": splits.get("test", 0),
        "environments_total": len(env_dirs),
        "environments_synthetic": len(env_dirs) - len(m100_envs),
        "environments_m100": len(m100_envs),
        "qcats": sorted(qcats),
        "roles": sorted(roles),
        "scoring_dimensions": _scoring_dimensions(),
        "adapters": ["direct_qa", "openai", "anthropic", "mcp"],
        "tool_families": ["slurm", "telemetry", "docs", "rbac", "facility"],
        "python_requires": _python_requires(),
        "license": "Apache-2.0",
    }


def _scoring_dimensions() -> int:
    """Count the non-zero weighted dimensions in the default scoring profile.

    This was hard-coded to 6 while ``default_hpc_v01`` has carried 7 weighted
    dimensions (``workflow`` is the seventh). The number is published in
    BENCHMARK_FACTS.json, so a hard-coded value is exactly the drift this script
    exists to prevent — derive it from the YAML like every other fact here.
    """
    profiles_path = ROOT / "benchmark" / "configs" / "scoring_profiles.yaml"
    text = profiles_path.read_text()
    # Match the default profile's `weights:` block: indented `name: number` lines.
    block = re.search(
        r"^  default_hpc_v01:.*?^    weights:\n((?:      \w+:\s*[0-9.]+\n)+)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if not block:
        raise SystemExit("check_facts: could not read default_hpc_v01 weights from scoring_profiles.yaml")
    weights = re.findall(r"^      (\w+):\s*([0-9.]+)$", block.group(1), re.MULTILINE)
    return sum(1 for _, value in weights if float(value) > 0)


def _project_version() -> str:
    text = (ROOT / "pyproject.toml").read_text()
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    return match.group(1) if match else "unknown"


def _python_requires() -> str:
    text = (ROOT / "pyproject.toml").read_text()
    match = re.search(r'^requires-python\s*=\s*"([^"]+)"', text, re.MULTILINE)
    return match.group(1) if match else "unknown"


def _rules(facts: dict[str, object]) -> list[tuple[str, str, str]]:
    """(relative path, regex that must match, human explanation)."""
    tasks = facts["tasks_total"]
    envs = facts["environments_total"]
    version = facts["version"]
    return [
        ("README.md", rf"\b{tasks} JSON task specs\b", f"README must state {tasks} task specs"),
        ("README.md", rf"\*\*{tasks}\*\*", f"README scope table must state {tasks} tasks"),
        ("README.md", rf"\*\*{envs}\*\*", f"README scope table must state {envs} environments"),
        ("llms.txt", rf"\b{tasks} tasks\b", f"llms.txt must state {tasks} tasks"),
        ("llms.txt", rf"\b{envs} deterministic environment", f"llms.txt must state {envs} envs"),
        ("docs/llms.txt", rf"\b{tasks} tasks\b", f"docs/llms.txt must state {tasks} tasks"),
        ("docs/index.md", rf"tasks-{tasks}-", f"docs/index.md tasks badge must read {tasks}"),
        ("docs/index.md", rf"environments-{envs}-", f"docs/index.md env badge must read {envs}"),
        ("docs/index.md", rf"version-{re.escape(str(version))}-", "docs/index.md version badge"),
        ("CITATION.cff", rf'version:\s*"?{re.escape(str(version))}"?', "CITATION.cff version"),
    ]


#: Surfaces that quote per-dimension weights and must agree with the YAML.
_WEIGHT_SURFACES = ("docs/framework/scoring-dimensions.md", "README.md")

#: Column order used by the Markdown weight tables on those surfaces.
_WEIGHT_ORDER = (
    "outcome",
    "tool_use",
    "grounding",
    "governance",
    "robustness",
    "efficiency",
    "workflow",
)


def _verify_weight_tables() -> list[str]:
    """Check that documented scoring weights match ``scoring_profiles.yaml``.

    The weights are the most consequential numbers AOBench publishes — a reader
    comparing two papers needs them to be right — and they are exactly the kind of
    table that rots silently after a profile is retuned.
    """
    # Keep the import local; only this check needs it.
    import yaml

    config = ROOT / "benchmark" / "configs" / "scoring_profiles.yaml"
    if not config.is_file():
        return [f"{config.relative_to(ROOT)}: missing — cannot verify weight tables"]

    profiles = (yaml.safe_load(config.read_text()) or {}).get("profiles", {})
    failures: list[str] = []

    for name, profile in profiles.items():
        weights = profile.get("weights", {})
        total = sum(weights.values())
        if abs(total - 1.0) > 1e-6:
            failures.append(f"scoring_profiles.yaml: profile '{name}' weights sum to {total}, not 1.0")

    default = profiles.get("default_hpc_v01", {}).get("weights", {})
    if not default:
        return [*failures, "scoring_profiles.yaml: no default_hpc_v01 profile"]

    # Match the exact table row rather than the individual numbers: every one of these
    # weights appears somewhere in both documents by coincidence, so a presence check
    # would pass on a table that is wrong in every cell.
    expected_row = " | ".join(f"{default.get(dim, 0.0):.2f}" for dim in _WEIGHT_ORDER)
    for rel in _WEIGHT_SURFACES:
        path = ROOT / rel
        if not path.exists():
            failures.append(f"{rel}: missing file")
        elif expected_row not in path.read_text():
            failures.append(
                f"{rel}: no default_hpc_v01 weight row matching the YAML. "
                f"Expected a table row containing: {expected_row}"
            )

    return failures


#: Number words that can spell a wrong scoring-dimension count in prose.
_NUMBER_WORDS = {
    "two": 2, "three": 3, "four": 4, "five": 5, "six": 6,
    "seven": 7, "eight": 8, "nine": 9, "ten": 10,
}

#: "dimension" is overloaded in these docs: CLEAR has five (E/A/R/C/L) and the
#: taxonomy has four, and neither is the weighted scoring profile. Only lines
#: that are clearly about *scoring* are checked.
_SCORING_CONTEXT = re.compile(r"scor|weighted|profile", re.IGNORECASE)
_NOT_SCORING = re.compile(r"\bCLEAR\b|taxonom", re.IGNORECASE)

#: A number bound tightly to "dimension" — "six dimensions", "6 dimensions",
#: "six-dimension scorecard". Digits are included: `llms.txt` said "12 scorers
#: across 6 dimensions", and that file exists to be quoted by answer engines.
_DIM_PHRASE = re.compile(
    r"\b(\d{1,2}|" + "|".join(_NUMBER_WORDS) + r")[\s-]dimension", re.IGNORECASE
)


def check_dimension_counts(expected: int) -> list[str]:
    """Fail on prose that states the wrong number of scoring dimensions.

    The weight *table* is checked on two surfaces, but the count is quoted in
    prose throughout the docs — `docs/guides/langfuse-integration.md` said "Six
    dimension scores attached to trace" long after `workflow` became the seventh
    weighted dimension. Documents drift one sentence at a time, so scan every
    Markdown surface rather than a hand-maintained list.
    """
    failures: list[str] = []
    roots = [ROOT / "docs", ROOT / "README.md", ROOT / "CONTRIBUTING.md",
             ROOT / "llms.txt", ROOT / "llms-full.txt"]
    for root in roots:
        if root.is_dir():
            paths = sorted([*root.rglob("*.md"), *root.rglob("llms*.txt")])
        else:
            paths = [root]
        for path in paths:
            if not path.exists():
                continue
            lines = path.read_text(encoding="utf-8").splitlines()
            for lineno, line in enumerate(lines, 1):
                # CLEAR and the taxonomy are often named in the heading above
                # rather than on the sentence itself, so look back a little.
                context = "\n".join(lines[max(0, lineno - 6):lineno])
                if _NOT_SCORING.search(context) or not _SCORING_CONTEXT.search(line):
                    continue
                for match in _DIM_PHRASE.finditer(line):
                    token = match.group(1).lower()
                    value = _NUMBER_WORDS.get(token) or int(token)
                    if value == expected:
                        continue
                    failures.append(
                        f"{path.relative_to(ROOT)}:{lineno}: says "
                        f"'{match.group(0)}' but the default profile weights "
                        f"{expected}: {line.strip()[:90]}"
                    )
    return failures


def verify(facts: dict[str, object]) -> list[str]:
    failures: list[str] = []
    for rel, pattern, explanation in _rules(facts):
        path = ROOT / rel
        if not path.exists():
            failures.append(f"{rel}: missing file")
            continue
        if not re.search(pattern, path.read_text()):
            failures.append(f"{rel}: {explanation} (no match for /{pattern}/)")

    # The package version must not drift from the project version. Deriving it from
    # installed distribution metadata makes drift structurally impossible, so that
    # form is accepted without comparing literals.
    init_text = (ROOT / "src" / "aobench" / "__init__.py").read_text()
    if "importlib.metadata" not in init_text:
        match = re.search(r'__version__\s*=\s*"([^"]+)"', init_text)
        if not match:
            failures.append("src/aobench/__init__.py: no __version__")
        elif match.group(1) != facts["version"]:
            failures.append(
                f"src/aobench/__init__.py: __version__ is {match.group(1)!r}, "
                f"pyproject says {facts['version']!r} — prefer deriving it from "
                "importlib.metadata so the two cannot drift"
            )

    failures.extend(_verify_weight_tables())
    failures.extend(check_dimension_counts(int(facts["scoring_dimensions"])))

    if FACTS_PATH.exists():
        stored = json.loads(FACTS_PATH.read_text())
        drifted = [k for k, v in facts.items() if k != "_comment" and stored.get(k) != v]
        if drifted:
            failures.append(
                "benchmark/BENCHMARK_FACTS.json is stale for: "
                + ", ".join(drifted)
                + " — run `python scripts/check_facts.py --write`"
            )
    else:
        failures.append("benchmark/BENCHMARK_FACTS.json missing — run with --write")

    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="refresh BENCHMARK_FACTS.json")
    args = parser.parse_args()

    facts = derive_facts()

    if args.write:
        FACTS_PATH.write_text(json.dumps(facts, indent=2) + "\n")
        print(f"wrote {FACTS_PATH.relative_to(ROOT)}")

    failures = verify(facts)
    if failures:
        print("Benchmark fact drift detected:\n", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        print(
            "\nThe corpus is the source of truth. Update the documented surface, "
            "not the corpus, unless the corpus genuinely changed.",
            file=sys.stderr,
        )
        return 1

    print(
        f"facts OK — {facts['tasks_total']} tasks "
        f"({facts['tasks_dev']} dev / {facts['tasks_test']} test), "
        f"{facts['environments_total']} environments, v{facts['version']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
